function:
  image: SET_ME
  memoryRequests: 64Mi
  cpuRequests: 75m
  memoryLimits: 500Mi
  cpuLimits: 300m
  triggerAuth:
    enabled: true
    create: true
  triggers:
    - type: azure-servicebus
      namespace: plum-servicebus-aat
      queueName: recipes
      queueLength: "5"
  aadIdentityName: cnp
  environment:
    FULLY_QUALIFIED_NAMESPACE: "plum-servicebus-aat.servicebus.windows.net"
    QUEUE: recipes
    MODE: "job"