function:
  image: SET_ME
  memoryRequests: 64Mi
  cpuRequests: 75m
  memoryLimits: 500Mi
  cpuLimits: 300m
  triggerAuth:
    enabled: true
    create: true
  triggers:
    - type: azure-servicebus
      namespace: toffee-servicebus-stg
      queueName: recipes
      queueLength: "5"
  aadIdentityName: toffee
  environment:
    FULLY_QUALIFIED_NAMESPACE: "toffee-servicebus-stg.servicebus.windows.net"
    QUEUE: recipes
    MODE: "job"