function:
  image: SET_ME
  memoryRequests: 64Mi
  cpuRequests: 75m
  memoryLimits: 500Mi
  cpuLimits: 300m
  triggerAuth:
    enabled: true
    create: true
  triggers:
    - type: azure-servicebus
      namespace: sds-keda-stg-01
      queueName: recipe
      queueLength: "5"
  aadIdentityName: toffee
  environment:
    FULLY_QUALIFIED_NAMESPACE: "sds-keda-stg-01.servicebus.windows.net"
    QUEUE: recipe-
    MODE: "job"