name: Cleanup PR resources
on:
  pull_request:
    types:
      - closed

env:
  # Common vars
  QUEUE_NAME: recipes-pr${{ github.event.number }}
  APP_NAME: recipe-receiver
  GITHUB_EVENT_NUMBER: ${{ github.event.number }}

permissions:
  id-token: write

jobs:
  cleanup:
    strategy:
      fail-fast: false
      matrix:
        project: ["sds", "cft"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Load ${{ matrix.project }} vars
        run: |
          cat ${VAR_FILE} >> $GITHUB_ENV
        shell: bash
        env:
          VAR_FILE: ${{ github.workspace }}/.github/workflows/${{ matrix.project }}.env

      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }} # DTS Recipe Receiver testing
          tenant-id: ${{ secrets.TENANT_ID }} # HMCTS.NET
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      # Clean up PR resources
      - name: Delete AKS resources
        run: |
          ./scripts/k8s.sh delete ${{ env.GITHUB_EVENT_NUMBER }}
        shell: bash

      - name: Delete PR queue
        run: |
          ./scripts/cleanup-infra.sh ${{ env.GITHUB_EVENT_NUMBER }}
        shell: bash
