name: Cleanup Resources
on:
  pull_request:
    types:
      - closed
env:
  # Common vars
  QUEUE_NAME: recipes-pr${{ github.event.number }}
  APP_NAME: recipe-receiver
  GITHUB_EVENT_NUMBER: ${{ github.event.number }}

jobs:
  cleanup:
    strategy:
      matrix:
        project: ["sds", "cft"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Load ${{ matrix.project }} vars
        run: |
          cat ${{ matrix.project }}.env >> $GITHUB_ENV
        shell: bash

      # Clean up PR resources
      - name: Delete AKS resources
        run: |
          ./scripts/k8s.sh delete
        shell: bash
        env:
          SB_RESOURCE_GROUP: ${{ env.SB_RESOURCE_GROUP }}
          SERVICE_BUS: ${{ env.SERVICE_BUS }}
          KUBE_NAMESPACE: ${{ env.KUBE_NAMESPACE }}
          CLUSTER_SUB: ${{ env.CLUSTER_SUB }}
          CLUSTER_RESOURCE_GROUP: ${{ env.CLUSTER_RESOURCE_GROUP }}
          CLUSTER_NAME: ${{ env.CLUSTER_NAME }}

      - name: Delete PR queue
        run: |
          ./scripts/cleanup-infra.sh ${{ env.QUEUE_NAME }}
        shell: bash
        env:
          LOCK_NAME: ${{ env.LOCK_NAME }}
          SERVICE_BUS: ${{ env.SERVICE_BUS }}
          SB_RESOURCE_GROUP: ${{ env.SB_RESOURCE_GROUP }}
          SUBSCRIPTION: ${{ env.SUBSCRIPTION }}
          KUBE_NAMESPACE: ${{ env.KUBE_NAMESPACE }}
          CLUSTER_SUB: ${{ env.CLUSTER_SUB }}
          CLUSTER_RESOURCE_GROUP: ${{ env.CLUSTER_RESOURCE_GROUP }}
          CLUSTER_NAME: ${{ env.CLUSTER_NAME }}