name: Cleanup Resources
on:
  pull_request:
    types:
      - closed
env:
  # Common vars
  PR_NUMBER: ${{ github.event.number }}
  QUEUE_NAME: recipes-pr${{ github.event.number }}
  APP_NAME: recipe-receiver

  # SDS vars
  SDS_CLUSTER_NAME: ss-dev-01-aks
  SDS_CLUSTER_RESOURCE_GROUP: ss-dev-01-rg
  SDS_SERVICE_BUS: toffee-servicebus-stg
  SDS_SB_RESOURCE_GROUP: toffee-shared-infrastructure-stg
  SDS_SUBSCRIPTION: 74dacd4f-a248-45bb-a2f0-af700dc4cf68
  SDS_KUBE_NAMESPACE: toffee
  SDS_LOCK_NAME: stg-lock

  # CFT vars
  CFT_CLUSTER_NAME: cft-preview-01-aks
  CFT_CLUSTER_RESOURCE_GROUP: cft-preview-01-rg
  CFT_SERVICE_BUS: plum-servicebus-aat
  CFT_SB_RESOURCE_GROUP: plum-shared-infrastructure-aat
  CFT_SUBSCRIPTION: 8b6ea922-0862-443e-af15-6056e1c9b9a4
  CFT_KUBE_NAMESPACE: cnp
  CFT_LOCK_NAME: prod-lock

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      # Set the target Azure Kubernetes Service (AKS) cluster.
#      - name: Switch to SDS AKS context
#        uses: azure/aks-set-context@v2
#        with:
#          admin: true
#          cluster-name: ${{ env.SDS_CLUSTER_NAME }}
#          resource-group: ${{ env.SDS_CLUSTER_RESOURCE_GROUP }}

      # Clean up PR resources
      - name: Clean up SDS resources
        run: |
          ./scripts/cleanup.sh ${{ env.QUEUE_NAME }}
        shell: bash
        env:
          LOCK_NAME: ${{ env.SDS_LOCK_NAME }}
          SERVICE_BUS: ${{ env.SDS_SERVICE_BUS }}
          SB_RESOURCE_GROUP: ${{ env.SDS_SB_RESOURCE_GROUP }}
          SUBSCRIPTION: ${{ env.SDS_SUBSCRIPTION }}
          KUBE_NAMESPACE: ${{ env.SDS_KUBE_NAMESPACE }}
          CLUSTER_SUB: ${{ env.SDS_CLUSTER_SUB }}
          CLUSTER_RESOURCE_GROUP: ${{ env.SDS_CLUSTER_RESOURCE_GROUP }}
          CLUSTER_NAME: ${{ env.SDS_CLUSTER_NAME }}

#      # Set the target Azure Kubernetes Service (AKS) cluster.
#      - name: Switch to CFT AKS context
#        uses: azure/aks-set-context@v2
#        with:
#          admin: true
#          cluster-name: ${{ env.CFT_CLUSTER_NAME }}
#          resource-group: ${{ env.CFT_CLUSTER_RESOURCE_GROUP }}

      # Clean up PR resources
      - name: Clean up CFT resources
        run: |
          ./scripts/cleanup.sh ${{ env.QUEUE_NAME }}
        shell: bash
        env:
          LOCK_NAME: ${{ env.CFT_LOCK_NAME }}
          SERVICE_BUS: ${{ env.CFT_SERVICE_BUS }}
          SB_RESOURCE_GROUP: ${{ env.CFT_SB_RESOURCE_GROUP }}
          SUBSCRIPTION: ${{ env.CFT_SUBSCRIPTION }}
          KUBE_NAMESPACE: ${{ env.CFT_KUBE_NAMESPACE }}
          CLUSTER_SUB: ${{ env.CFT_CLUSTER_SUB }}
          CLUSTER_RESOURCE_GROUP: ${{ env.CFT_CLUSTER_RESOURCE_GROUP }}
          CLUSTER_NAME: ${{ env.CFT_CLUSTER_NAME }}
