name: Cleanup old Resources
on:
  workflow_dispatch:
  schedule:
      - cron: '* 6 * * 1'
env:
  # Common vars
  APP_NAME: recipe-receiver

jobs:
  cleanup:
    strategy:
      matrix:
        project: ["sds", "cft"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Load ${{ matrix.project }} vars
        run: |
          cat ${VAR_FILE} >> $GITHUB_ENV
        shell: bash
        env:
          VAR_FILE: ${{ github.workspace }}/.github/workflows/${{ matrix.project }}.env

      - uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      # Clean up old PR resources
      - name: Clean up old resources
        run: |
          ./scripts/cleanup-old-resources.sh
        shell: bash
