name: Cleanup Resources
on:
  pull_request:
    types:
      - closed
env:
  CLUSTER_NAME: ss-dev-01-aks
  CLUSTER_RESOURCE_GROUP: ss-dev-01-rg
  APP_NAME: recipe-receiver
  SERVICE_BUS: toffee-servicebus-stg
  SB_RESOURCE_GROUP: toffee-shared-infrastructure-stg
  PR_NUMBER: ${{ github.event.number }}
  QUEUE_NAME: recipes-pr${{ github.event.number }}
  SUBSCRIPTION: 74dacd4f-a248-45bb-a2f0-af700dc4cf68
  KUBE_NAMESPACE: toffee

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set the target Azure Kubernetes Service (AKS) cluster.
      - uses: azure/aks-set-context@v2
        with:
          admin: true
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      # Clean up PR resources
      - name: Clean up resources
        run: |
          ./scripts/cleanup.sh ${{ env.QUEUE_NAME }}
        shell: bash
