name: Cleanup Resources
on:
  pull_request:
    types:
      - closed
env:
  # Common vars
  QUEUE_NAME: recipes-pr${{ github.event.number }}
  APP_NAME: recipe-receiver
  GITHUB_EVENT_NUMBER: ${{ github.event.number }}

  # SDS vars
  SDS_CLUSTER_NAME: ss-dev-01-aks
  SDS_CLUSTER_RESOURCE_GROUP: ss-dev-01-rg
  SDS_SERVICE_BUS: toffee-servicebus-stg
  SDS_SB_RESOURCE_GROUP: toffee-shared-infrastructure-stg
  SDS_SUBSCRIPTION: 74dacd4f-a248-45bb-a2f0-af700dc4cf68
  SDS_KUBE_NAMESPACE: toffee
  SDS_LOCK_NAME: stg-lock
  SDS_CLUSTER_SUB: 867a878b-cb68-4de5-9741-361ac9e178b6

  # CFT vars
  CFT_CLUSTER_NAME: cft-preview-01-aks
  CFT_CLUSTER_RESOURCE_GROUP: cft-preview-01-rg
  CFT_SERVICE_BUS: plum-servicebus-aat
  CFT_SB_RESOURCE_GROUP: plum-shared-infrastructure-aat
  CFT_SUBSCRIPTION: 1c4f0704-a29e-403d-b719-b90c34ef14c9
  CFT_KUBE_NAMESPACE: cnp
  CFT_LOCK_NAME: prod-lock
  CFT_CLUSTER_SUB: 8b6ea922-0862-443e-af15-6056e1c9b9a4

jobs:
  cleanupSDS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Clean up PR resources
      - name: Delete AKS resources
        run: |
          ./scripts/k8s.sh delete
        shell: bash
        env:
          SB_RESOURCE_GROUP: ${{ env.SDS_SB_RESOURCE_GROUP }}
          SERVICE_BUS: ${{ env.SDS_SERVICE_BUS }}
          KUBE_NAMESPACE: ${{ env.SDS_KUBE_NAMESPACE }}
          CLUSTER_SUB: ${{ env.SDS_CLUSTER_SUB }}
          CLUSTER_RESOURCE_GROUP: ${{ env.SDS_CLUSTER_RESOURCE_GROUP }}
          CLUSTER_NAME: ${{ env.SDS_CLUSTER_NAME }}

      - name: Delete PR queue
        run: |
          ./scripts/cleanup-infra.sh ${{ env.QUEUE_NAME }}
        shell: bash
        env:
          LOCK_NAME: ${{ env.SDS_LOCK_NAME }}
          SERVICE_BUS: ${{ env.SDS_SERVICE_BUS }}
          SB_RESOURCE_GROUP: ${{ env.SDS_SB_RESOURCE_GROUP }}
          SUBSCRIPTION: ${{ env.SDS_SUBSCRIPTION }}
          KUBE_NAMESPACE: ${{ env.SDS_KUBE_NAMESPACE }}
          CLUSTER_SUB: ${{ env.SDS_CLUSTER_SUB }}
          CLUSTER_RESOURCE_GROUP: ${{ env.SDS_CLUSTER_RESOURCE_GROUP }}
          CLUSTER_NAME: ${{ env.SDS_CLUSTER_NAME }}

  cleanupCFT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}



      # Clean up PR resources
      - name: Delete AKS resources
        run: |
          ./scripts/k8s.sh delete
        shell: bash
        env:
          SB_RESOURCE_GROUP: ${{ env.CFT_SB_RESOURCE_GROUP }}
          SERVICE_BUS: ${{ env.CFT_SERVICE_BUS }}
          KUBE_NAMESPACE: ${{ env.CFT_KUBE_NAMESPACE }}
          CLUSTER_SUB: ${{ env.CFT_CLUSTER_SUB }}
          CLUSTER_RESOURCE_GROUP: ${{ env.CFT_CLUSTER_RESOURCE_GROUP }}
          CLUSTER_NAME: ${{ env.CFT_CLUSTER_NAME }}

      - name: Delete PR queue
        run: |
          ./scripts/cleanup-infra.sh ${{ env.QUEUE_NAME }}
        shell: bash
        env:
          LOCK_NAME: ${{ env.CFT_LOCK_NAME }}
          SERVICE_BUS: ${{ env.CFT_SERVICE_BUS }}
          SB_RESOURCE_GROUP: ${{ env.CFT_SB_RESOURCE_GROUP }}
          SUBSCRIPTION: ${{ env.CFT_SUBSCRIPTION }}
          KUBE_NAMESPACE: ${{ env.CFT_KUBE_NAMESPACE }}
          CLUSTER_SUB: ${{ env.CFT_CLUSTER_SUB }}
          CLUSTER_RESOURCE_GROUP: ${{ env.CFT_CLUSTER_RESOURCE_GROUP }}
          CLUSTER_NAME: ${{ env.CFT_CLUSTER_NAME }}
