name: Go

on:
  pull_request:
    paths:
      - 'pkg/**'
      - 'main.go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Go fmt
      run: go fmt
      env:
        GOOS: darwin
        GOARCH: amd64
      
# Add at later date 
#     - name: Test
#       run: go test -v ./...
