name: Promote Keda test app

on:
  push:
    branches:
      - master

env:
  # Common vars
  GITHUB_EVENT_NUMBER: ${{ github.event.number }}
  APP_NAME: recipe-receiver
  QUEUE_NAME: recipes-pr${{ github.event.number }}
  HELM_VERSION: v3.9.0
  VAR_FILE_PATH: ${{ github.workspace }}/.github/workflows

jobs:
  promote:
    strategy:
      matrix:
        project: ["sds", "cft"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      # Load Project environment variables
      - name: Load ${{ matrix.project }} vars
        run: |
          env
        shell: bash

#       # Load Project environment variables
#       - name: Load ${{ matrix.project }} vars
#         run: |
#           cat ${VAR_FILE} >> $GITHUB_ENV
#         shell: bash
#         env:
#           VAR_FILE: ${{ github.workspace }}/.github/workflows/${{ matrix.project }}.env
