name: Promote Keda test app

on:
  pull_request:
    types:
      - closed
env:
  # Common vars
  GITHUB_EVENT_NUMBER: ${{ github.event.number }}
  APP_NAME: recipe-receiver
  VAR_FILE_PATH: ${{ github.workspace }}/.github/workflows

jobs:
  promote:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        project: ["sds", "cft"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      # Load Project environment variables
      - name: Load ${{ matrix.project }} vars
        run: |
          cat ${VAR_FILE} >> $GITHUB_ENV
        shell: bash
        env:
          VAR_FILE: ${{ env.VAR_FILE_PATH }}/${{ matrix.project }}.env

      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }} # DTS Recipe Receiver testing
          tenant-id: ${{ secrets.TENANT_ID }} # HMCTS.NET
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      # Container build and push to an Azure Container Registry (ACR)
      - name: Promote PR Image to Prod
        run: |
          ./scripts/docker.sh prod
        shell: bash
        if: ${{ success() }}

      - name: Az logout
        run: |
          az logout
        shell: bash
        if: ${{ always() }}
